//
// Created by Chandler Desforges on 11/18/24.
//

#ifndef BOOTLEG_MARIO_PHYSICSSPRITETYPE_H
#define BOOTLEG_MARIO_PHYSICSSPRITETYPE_H

enum PhysicsSpriteType {MARIO, LUIGI, GOOMBA, KOOPA, ITEM, WORLD, SPECIAL_BLOCK, BLOCK, PIPE, BACKGROUND};

#endif //BOOTLEG_MARIO_PHYSICSSPRITETYPE_H
